[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[edge_functions]]
  function = "proxy"
  path = "/proxy/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200