[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/proxy/model"
  to = "https://api.fish.audio/model"
  status = 200
  force = true

[[redirects]]
  from = "/proxy/tts"
  to = "https://api.fish.audio/v1/tts"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200